AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  CountComments: false
  Max: 15
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Guardfile'
